#!/usr/bin/env python3
"""Adapt the pinned upstream release jobs; requires PyYAML, used only in CI/dev."""
import argparse
import copy
from pathlib import Path
import sys
import yaml

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / '.github/workflows/release-builds.yml'


class Dumper(yaml.SafeDumper):
    pass


def string(dumper, value):
    return dumper.represent_scalar('tag:yaml.org,2002:str', value,
                                   style='|' if '\n' in value else None)


Dumper.add_representer(str, string)


def source_steps():
    return [
        {'name': 'Download patched source', 'uses': 'actions/download-artifact@v7',
         'with': {'name': 'patched-source', 'path': '${{ runner.temp }}/isa-source'}},
        {'name': 'Extract patched source', 'shell': 'bash',
         # Git Bash tar interprets a Windows drive colon as a remote host.
         # Let Bash handle both Windows paths, including the destination.
         'run': 'cd "$GITHUB_WORKSPACE"\ntar -xzf - < "$RUNNER_TEMP/isa-source/patched-source.tar.gz"'},
    ]


def generate():
    upstream = yaml.safe_load((ROOT / 'llama.cpp/.github/workflows/release.yml').read_text())
    jobs = {}
    for name, original in upstream['jobs'].items():
        if name in ('check-release', 'release', 'ui-publish'):
            continue
        if name == 'ui-build':
            job = yaml.safe_load((ROOT / 'llama.cpp/.github/workflows/ui-build.yml').read_text())['jobs']['build']
        else:
            job = copy.deepcopy(original)
        job.pop('if', None)
        needs = [n for n in job.pop('needs', []) if n != 'check-release']
        if needs:
            job['needs'] = needs
        job['permissions'] = {'contents': 'read'}
        job['timeout-minutes'] = 180
        if 'strategy' in job:
            job['strategy']['fail-fast'] = False
        if job.get('runs-on') == 'ubuntu-slim':
            job['runs-on'] = 'ubuntu-24.04'
        # s390x is an upstream custom runner, unavailable to ordinary forks.
        if name == 'ubuntu-cpu':
            job['strategy']['matrix']['include'] = [row for row in job['strategy']['matrix']['include']
                                                   if row['build'] != 's390x']
        steps = []
        for step in job['steps']:
            uses = step.get('uses', '')
            if uses.startswith('actions/checkout@'):
                steps.extend(source_steps())
            elif uses == './.github/actions/get-tag-name':
                steps.append({'name': 'Release identifier', 'id': 'tag', 'shell': 'bash',
                              'env': {'RELEASE_TAG': '${{ inputs.tag }}'},
                              'run': 'echo "name=$RELEASE_TAG" >> "$GITHUB_OUTPUT"'})
            elif uses == './.github/actions/ccache-clear':
                continue  # No cache deletion permissions needed in this project.
            elif name == 'ui-build' and step.get('id') == 'version':
                steps.append({'name': 'UI version', 'id': 'version', 'shell': 'bash',
                              'env': {'RELEASE_TAG': '${{ inputs.tag }}'},
                              'run': 'echo "ui_version=$RELEASE_TAG" >> "$GITHUB_OUTPUT"'})
            else:
                if uses.startswith('actions/upload-artifact@'):
                    step.setdefault('with', {})['if-no-files-found'] = 'error'
                    step['with']['retention-days'] = 7
                    step['with']['overwrite'] = True
                # CPU binaries are injected into Windows backend zips upstream.
                if name == 'windows-cpu' and step.get('id') == 'pack_artifacts':
                    steps.append({'name': 'Include license and provenance',
                                  'run': 'Copy-Item LICENSE build/bin/Release/\nCopy-Item -Recurse isa-release build/bin/Release/'})
                steps.append(step)
                if name == 'macos-cpu' and step.get('id') == 'cmake_build':
                    steps.append({
                        'name': 'Compile TurboQuant Metal shaders',
                        'if': "matrix.arch == 'arm64'",
                        'shell': 'bash',
                        'run': '''# Embedded shader sources are normally compiled only at runtime.
if ! xcrun --sdk macosx metal --version; then
  xcodebuild -downloadComponent MetalToolchain
fi
for kind in fa quantize; do
  xcrun --sdk macosx metal -std=metal3.0 -DGGML_METAL_EMBED_LIBRARY \\
    -c "build/ggml/src/ggml-metal/autogenerated/ggml-metal-embed-$kind.metal" \\
    -o "$RUNNER_TEMP/isa-$kind.air"
  xcrun --sdk macosx metallib "$RUNNER_TEMP/isa-$kind.air" \\
    -o "$RUNNER_TEMP/isa-$kind.metallib"
done
''',
                    })
        job['steps'] = steps
        jobs[name] = job
    env = upstream['env']
    env['CMAKE_ARGS'] += (' -DCMAKE_BUILD_TYPE=Release'
                          ' -DLLAMA_BUILD_NUMBER=${{ github.run_number }}'
                          ' -DLLAMA_BUILD_COMMIT=isa-${{ github.sha }}')
    workflow = {'name': 'Release builds (generated)',
                'on': {'workflow_call': {'inputs': {'tag': {'required': True, 'type': 'string'}}}},
                'permissions': {'contents': 'read'}, 'env': env, 'jobs': jobs}
    return ('# Generated by .github/scripts/generate-build-workflow.py; do not edit.\n'
            '# Build recipes and local actions come from the pinned llama.cpp submodule (MIT).\n'
            + yaml.dump(workflow, Dumper=Dumper, sort_keys=False, width=120))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            sys.exit('Release build workflow is stale; run .github/scripts/generate-build-workflow.py')
    else:
        OUTPUT.write_text(generated)
